### ISSUE TITLE
Snake can move into itself

### ISSUE THREAD

**Issue by aaron-coding** [appacademy/snake.js#1]
Snake can move into itself ( back into itself ) if the user uses arrow keys too quickly.

e.g., if snake is moving right, and user presses "w" and "a" really fast, the snake registers an "up" turn, but does not actually move, then the snake registers a "left" turn and then the next "move" is called.

The snake runs into itself without moving into any other square first.

**Comment by rglassett** [comment]
This should be fixed as of 3d48c14. Thanks!
